name: "@lando/core"
hooks:
  app:
    init:
      - "./hooks/test.js"
  cli:
    init:
      - "./hooks/test.js"
  product:
    init:
      - "./hooks/test.js"
  lando:
    init:
      - "./hooks/test.js"

registry:
  app:
    app: "./lib/app"
    appfile-app: "./components/appfile-app"
    landofile-legacy-app: "./components/legacy-app"
  engine:
    # docker-colima: "./components/docker-colima"
    docker-desktop: "./components/docker-desktop"
    docker-engine: "./components/docker-engine"
    # docker-colima:
    # podman:

  # orchestrator:
  #   docker-compose-1:
  #   docker-compose-2:
  legacy:
    services:
      _compose: "./services/compose"
  library:
    config: "./lib/config"
    debug: "./lib/debug"
    module-loader: "./lib/module-loader"
    plugin: "./lib/plugin"
    templator: "./lib/templator"
  plugin-installer:
    docker-plugin-installer: "./components/docker-plugin-installer"
  product:
    product: "./lib/product"
    lando: "./components/lando"
  storage:
    file-storage: "./components/file-storage"
    no-storage: "./components/no-storage"

tasks:
  config: "./tasks/config"
  destroy: "./tasks/destroy"
  info: "./tasks/info"
  list: "./tasks/list"
  logs: "./tasks/logs"
  poweroff: "./tasks/poweroff"
  rebuild: "./tasks/rebuild"
  restart: "./tasks/restart"
  share: "./tasks/share"
  start: "./tasks/start"
  stop: "./tasks/stop"
  version: "./tasks/version"
