name: "@lando/core"
hooks:
  product:
    init:
      - "./hooks/test.js"
  lando:
    init:
      - "./hooks/test.js"

registry:
  app:
    app: "./lib/app"
    app-v3: "./components/landofile-v3-app"
    landofile-v3-app: "./components/landofile-v3-app"
  engine:
    # docker-colima: "./components/docker-colima"
    docker-desktop: "./components/docker-desktop"
    docker-engine: "./components/docker-engine"
    # docker-colima:
    # podman:

  # orchestrator:
  #   docker-compose-1:
  #   docker-compose-2:
  legacy:
    services:
      _compose: "./services/compose"
  plugin-installer:
    docker-plugin-installer: "./components/docker-plugin-installer"
  product:
    lando: "./components/lando"
  storage:
    file-storage: "./components/file-storage"
    no-storage: "./components/no-storage"

tasks:
  config: "./tasks/config"
  destroy: "./tasks/destroy"
  info: "./tasks/info"
  list: "./tasks/list"
  logs: "./tasks/logs"
  poweroff: "./tasks/poweroff"
  rebuild: "./tasks/rebuild"
  restart: "./tasks/restart"
  share: "./tasks/share"
  start: "./tasks/start"
  stop: "./tasks/stop"
  version: "./tasks/version"
