name: lando-the-sitename-that-never-ends-it-goes-on-and-on-my-friends-no-seriously-it-keeps-going-on-and-on
services:
  defaults:
    type: nginx
    ssl: true

plugins:
  "@lando/core": ./../..

# get this app to use the new v4 runtime
runtime: 4
config:
  core:
    dev-mode: 1
    telemetry: 0
