name: lando-scanner
services:
  scanme:
    type: apache
  moreports:
    type: apache
    moreHttpPorts:
      - '8888'
  dontlookatme:
    type: apache
    scanner: false

plugins:
  "@lando/core": ./../..

# get this app to use the new v4 runtime
runtime: 4
config:
  core:
    dev-mode: 1
    telemetry: 0
