name: "XYŹ | AFFAIR"
services:
  defaults:
    type: apache

plugins:
  "@lando/core": ./../..

# get this app to use the new v4 runtime
runtime: 4
config:
  core:
    development: true
    telemetry: false
